#!/usr/bin/env sh

setup_network() {
	./common/setup-eth0-udev-rules "f8:32:e4:9c:7a:33"
	./common/assert-avahi-daemon
	./common/setup-br0 "192.168.40.202"
}

setup_nas() {
	apt install -y nfs-kernel-server rpcbind
	perl -pi -e 's/^OPTIONS/#OPTIONS/' /etc/default/rpcbind
	echo "rpcbind: 192.168.40." >>/etc/hosts.allow
	systemctl restart rpcbind.service

	echo "/example 192.168.40.0/255.255.255.0(rw,no_root_squash,subtree_check)" >>/etc/exports
	exportfs -a
	/etc/init.d/nfs-kernel-server reload
}

setup_locale() {
	tee /etc/locale.conf <<-EOF
		LANG="en_US.UTF-8"
		LANGUAGE="en_US.UTF-8"
		LC_NAME="en_US.UTF-8"
		LC_TELEPHONE="en_US.UTF-8"
		LC_IDENTIFICATION="en_US.UTF-8"
		LC_CTYPE="en_US.UTF-8"
		LC_NUMERIC="en_US.UTF-8"
		LC_MESSAGES="en_US.UTF-8"
		LC_COLLATE="en_US.UTF-8"
		LC_MONETARY="en_US.UTF-8"
		LC_PAPER="en_US.UTF-8"
		LC_MEASUREMENT="en_US.UTF-8"
		LC_ADDRESS="en_US.UTF-8"
		LC_TIME="en_US.UTF-8"

		# vi: ft=sh
	EOF

	apt install -y locales
	echo 'en_US.UTF-8 UTF-8' >>/etc/locale.gen
	locale-gen
}

setup_time() {
	dpkg-reconfigure tzdata

	apt-get install -y chrony
}

setup_network
setup_nas
setup_locale
setup_time
