#!/usr/bin/env sh

setup_network() {
	./common/setup-eth0-udev-rules "f8:32:e4:9c:7a:33"
	./common/assert-avahi-daemon
	./common/setup-br0 "192.168.40.202"
}

setup_nas() {
	apt install -y nfs-kernel-server rpcbind
	perl -pi -e 's/^OPTIONS/#OPTIONS/' /etc/default/rpcbind
	echo "rpcbind: 192.168.40." >>/etc/hosts.allow
	systemctl restart rpcbind.service

	echo "/example 192.168.40.0/255.255.255.0(rw,no_root_squash,subtree_check)" >>/etc/exports
	exportfs -a
	/etc/init.d/nfs-kernel-server reload
}

setup_network
setup_nas
